# Generated by Django 5.0.2 on 2024-03-18 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=20)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('arenaId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('arenaName', models.CharField(max_length=50)),
                ('arenaCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figureName', models.CharField(max_length=100)),
                ('figureGenre', models.CharField(max_length=100)),
                ('figurePicture', models.ImageField(blank=True, null=True, upload_to='figure_images/')),
                ('figureAbout', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('userPassword', models.CharField(default='temp_password', max_length=20)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhoneNumber', models.CharField(max_length=10)),
                ('userAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField(default='12:00')),
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventDescription', models.CharField(max_length=250)),
                ('eventStatus', models.CharField(max_length=10)),
                ('eventGenre', models.CharField(default='none', max_length=100)),
                ('eventImage', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('arenaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.arena')),
                ('figureId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.figure')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('reviewRating', models.IntegerField()),
                ('reviewTitle', models.CharField(max_length=100)),
                ('reviewText', models.CharField(max_length=500)),
                ('reviewDate', models.DateField()),
                ('eventID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.event')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewImage', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tixx.review')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.AutoField(primary_key=True, serialize=False)),
                ('seatNum', models.CharField(max_length=5)),
                ('ticketQR', models.CharField(max_length=250)),
                ('ticketPrice', models.IntegerField()),
                ('ticketType', models.CharField(max_length=10)),
                ('arenaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.arena')),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.event')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatId', models.AutoField(primary_key=True, serialize=False)),
                ('seatNumber', models.IntegerField()),
                ('arenaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.arena')),
                ('ticketId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paymentAmount', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=10)),
                ('paymentDate', models.DateField()),
                ('transactionId', models.CharField(max_length=10)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.user')),
            ],
        ),
    ]
