# Generated by Django 5.0.2 on 2024-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tixx", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ticket", name="zone", field=models.IntegerField(default=1),
        ),
    ]
