# Generated by Django 5.0.3 on 2024-03-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=20)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('arenaId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('arenaName', models.CharField(max_length=20)),
                ('arenaCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figureName', models.CharField(max_length=100)),
                ('figureGenre', models.CharField(max_length=100)),
                ('figurePicture', models.ImageField(blank=True, null=True, upload_to='figure_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventGenre',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventImage',
        ),
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='temp_password', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='arenaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.arena'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='arenaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.arena'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatId', models.AutoField(primary_key=True, serialize=False)),
                ('seatNumber', models.IntegerField()),
                ('arenaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.arena')),
                ('ticketId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.ticket')),
            ],
        ),
    ]
