# Generated by Django 5.0.3 on 2024-03-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='eventID',
        ),
    ]
