# Generated by Django 5.0.3 on 2024-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0002_admin_arena_figure_remove_event_eventgenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventGenre',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='eventImage',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
