# Generated by Django 5.0.3 on 2024-03-19 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0002_remove_review_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewFigure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tixx.figure'),
        ),
    ]
