# Generated by Django 5.0.2 on 2024-03-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tixx", "0002_admin_arena_figure_user_userpassword_and_more"),
        ("tixx", "0002_ticket_available_ticket_zone"),
    ]

    operations = []
