# Generated by Django 5.0.3 on 2024-03-08 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0002_event_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhoneNumber', models.IntegerField()),
                ('userAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='eventDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='eventLocation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='eventDescription',
            field=models.CharField(default='No description provided', max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='eventId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.CharField(default='No Name provided', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(default='No status provided', max_length=10),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.IntegerField(primary_key=True, serialize=False)),
                ('seatNum', models.CharField(max_length=5)),
                ('ticketQR', models.CharField(max_length=250)),
                ('ticketPrice', models.IntegerField()),
                ('ticketType', models.CharField(max_length=10)),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.event')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reviewRating', models.IntegerField()),
                ('reviewTitle', models.CharField(max_length=10)),
                ('reviewText', models.CharField(max_length=50)),
                ('reviewDate', models.DateField()),
                ('eventID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paymentAmount', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=10)),
                ('paymentDate', models.DateField()),
                ('transactionId', models.CharField(max_length=10)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.user')),
            ],
        ),
    ]
