# Generated by Django 5.0.3 on 2024-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0003_user_rename_date_event_eventdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(default='No id provided', max_length=100, primary_key=True, serialize=False),
        ),
    ]
