# Generated by Django 5.0.2 on 2024-03-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0003_customuser_rename_date_event_eventdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventLocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='eventId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.event'),
        ),
    ]
