# Generated by Django 5.0.3 on 2024-03-19 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0003_review_reviewfigure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewRating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
