# Generated by Django 5.0.3 on 2024-03-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0003_alter_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organiserCredentials',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
