# Generated by Django 5.0.3 on 2024-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0004_user_organisercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
