# Generated by Django 5.0.2 on 2024-03-21 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0004_alter_review_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='figureName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewRating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
