# Generated by Django 5.0.2 on 2024-03-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0004_alter_event_eventlocation_alter_event_eventstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventLocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='eventId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.event'),
        ),
    ]
