# Generated by Django 5.0.3 on 2024-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0005_user_userprofilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
