# Generated by Django 5.0.2 on 2024-03-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0005_alter_figure_figurename_alter_review_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='carouselImage',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
    ]
