# Generated by Django 5.0.3 on 2024-03-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0005_alter_event_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
