# Generated by Django 5.0.3 on 2024-03-26 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0006_figure_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tixx.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tixx.user')),
            ],
        ),
    ]
