# Generated by Django 5.0.3 on 2024-04-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0007_event_admincheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
