# Generated by Django 5.0.3 on 2024-04-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0008_event_isrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userDescription',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
