# Generated by Django 5.0.3 on 2024-03-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
