# Generated by Django 5.0.3 on 2024-04-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0009_user_userdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoriteFigure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tixx.figure'),
        ),
    ]
