# Generated by Django 5.0.3 on 2024-04-06 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0009_alter_user_managers_user_city_user_favoritefigure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userReview',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
