# Generated by Django 5.0.3 on 2024-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0010_user_favoritefigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
    ]
