# Generated by Django 5.0.2 on 2024-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0010_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOrganiser',
            field=models.BooleanField(default=False),
        ),
    ]
