# Generated by Django 5.0.3 on 2024-04-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0012_remove_user_backgroundimage_user_miniimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoriteSongSpotifyId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
