# Generated by Django 5.0.3 on 2024-04-04 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0013_user_favoritesongspotifyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userReview',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
