# Generated by Django 5.0.3 on 2024-04-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tixx', '0017_user_city_user_postalcode_user_stateprovince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userProfilePicture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
