
from django.core.management.base import BaseCommand
from tixx.models import Figure

class Command(BaseCommand):
    help = 'Imports Figure data into the database'

    def handle(self, *args, **kwargs):

        data = [
            ["1","Hip-Hop","figure_images/Drake.jpg","Drake, born Aubrey Drake Graham on October 24, 1986, is a Canadian rapper, singer, songwriter, actor, and entrepreneur. Hailing from Toronto, Ontario, Canada, Drake rose to prominence in the music industry with his captivating blend of rap and R&B.  Throughout his illustrious career, Drake has achieved numerous milestones and accolades. He first gained recognition for his role as Jimmy Brooks on the television series Degrassi: The Next Generation. Transitioning to music, Drake released his debut mixtape, 'Room for Improvement,' in 2006, followed by 'Comeback Season' in 2007.  In 2009, Drake released his third mixtape, 'So Far Gone,' which included the hit single 'Best I Ever Had' and propelled him to mainstream success. This led to the release of his debut studio album, 'Thank Me Later,' in 2010, which debuted at number one on the Billboard 200 chart.  Drake's subsequent albums, including 'Take Care' (2011), 'Nothing Was the Same' (2013), 'Views' (2016), and 'Scorpion' (2018), have all achieved critical and commercial success, cementing his status as one of the best-selling artists of all time. He has won numerous awards, including multiple Grammy Awards and Billboard Music Awards.  Aside from his music career, Drake has ventured into acting, appearing in films such as 'Charlie Bartlett' and 'Ice Age: Continental Drift' and hosting Saturday Night Live. He also founded the record label OVO Sound and the clothing line October's Very Own (OVO).  Drake's impact on the music industry and popular culture is undeniable, with his innovative sound and versatility influencing countless artists worldwide. He continues to push boundaries and redefine genres, solidifying his legacy as one of the most influential figures in contemporary music.","Drake","carousel_images/771181.jpg"],
            ["2","Hip-Hop","figure_images/kanye.webp","Kanye West is a groundbreaking figure in the music industry, known for his innovative approach to hip-hop and influential contributions to pop culture. Born in Atlanta in 1977, West rose to fame as a producer before launching his solo rap career with the critically acclaimed album 'The College Dropout' in 2004. Throughout his career, West has pushed artistic boundaries, blending genres and experimenting with sound. His discography includes hits like 'Gold Digger,' 'Stronger,' and 'Heartless.' Beyond music, West is recognized for his fashion ventures, outspoken personality, and controversial public statements. Despite polarizing opinions, he remains a cultural icon, shaping the landscape of music and entertainment.","Ye","carousel_images/jc3gu9ckqs481.jpg"],
            ["3","Rock","figure_images/foo.webp","The Foo Fighters are an iconic American rock band formed in 1994 by Nirvana drummer Dave Grohl after the death of Kurt Cobain. With a dynamic sound blending alternative rock, post-grunge, and punk influences, the Foo Fighters quickly rose to prominence with their self-titled debut album in 1995, featuring hits like 'This Is a Call' and 'Big Me.' Over the years, they've released numerous critically acclaimed albums, including 'The Colour and the Shape,' 'There Is Nothing Left to Lose,' and 'Wasting Light.' Renowned for their energetic live performances and Grohl's charismatic stage presence, the Foo Fighters have become one of the most enduring and beloved rock bands of their generation.","Foo Fighters","carousel_images/198549.jpg"],
            ["4","Hip-Hop","figure_images/lucki.webp","Lucki, born Lucki Camel, is a rising rapper hailing from Chicago, Illinois. With a distinctive style characterized by introspective lyricism and laid-back delivery, Lucki has carved out a unique niche in the hip-hop landscape. Known for his candid exploration of personal struggles, addiction, and urban life, Lucki's music resonates with authenticity and raw emotion. He first gained recognition with his mixtape 'Alternative Trap' and has since released several acclaimed projects, including 'Freewave' series and 'Almost There' EP. Lucki continues to captivate audiences with his evocative storytelling and has established himself as a prominent figure in the underground rap scene.","LUCKI","carousel_images/wp11559911.webp"],
            ["5","Hip-Hop","figure_images/future.webp","Future, born Nayvadius DeMun Wilburn, is an influential rapper and songwriter originating from Atlanta, Georgia. Renowned for his innovative approach to trap music, Future has become a dominant force in the hip-hop industry. His distinctive blend of melodic hooks, autotuned vocals, and gritty lyrics has garnered widespread acclaim and commercial success. With hit albums like 'DS2,' 'Honest,' and 'Future,' he has solidified his status as one of the most prolific artists of his generation. Future's music often explores themes of fame, wealth, love, and resilience, resonating with audiences worldwide. His impact on the genre continues to shape contemporary rap culture, cementing his legacy as a visionary artist.","Future","carousel_images/25c4cd4a979d7af9f8b5b91dcc3af209.jpg"],
            ["6","Hip-Hop","figure_images/carti.webp","Playboi Carti, born Jordan Terrell Carter, is an American rapper, singer, and songwriter known for his unique style and distinctive sound. Emerging from Atlanta's underground rap scene, Carti gained attention with his breakout mixtape 'Playboi Carti' in 2017, featuring hit tracks like 'Magnolia' and 'wokeuplikethis*.' His music often incorporates elements of trap, punk, and experimental hip-hop, characterized by catchy ad-libs, infectious beats, and high-energy delivery. Carti's enigmatic persona and fashion-forward aesthetic have further solidified his status as a trendsetter in contemporary rap culture. With his innovative approach to music and fashion, Playboi Carti continues to captivate audiences and push boundaries in the music industry.","Playboi Carti","carousel_images/05f381e76a5d22be1a780f8f232b5077.jpg"],
            ["7","Pop","figure_images/frankk.webp","Frank Ocean is a profoundly influential singer-songwriter known for his introspective lyrics and innovative approach to R&B and hip-hop. Born Christopher Edwin Breaux in 1987, Ocean gained recognition as a member of the alternative hip-hop collective Odd Future before launching his solo career. His debut studio album, 'Channel Orange' (2012), received widespread critical acclaim and earned him a Grammy Award. Ocean's music often explores themes of love, identity, and societal issues with a unique blend of soulful melodies and experimental production. He's also celebrated for his honesty about his sexuality, making him an icon for LGBTQ+ representation in the music industry.","Frank Ocean","carousel_images/frankoo.png"],
            ["8","Classic-Pop","figure_images/sinatraa.jpg","Frank Sinatra, born Francis Albert Sinatra in 1915, was a legendary American singer, actor, and cultural icon. Renowned as 'The Voice,' Sinatra's career spanned several decades and encompassed various musical styles, including jazz, swing, and traditional pop. He rose to fame in the 1940s as a solo artist and became one of the best-selling music artists of all time. Sinatra's smooth vocal delivery, impeccable phrasing, and charismatic stage presence captivated audiences worldwide. Beyond his musical achievements, he also found success in film, winning an Academy Award for Best Supporting Actor. Sinatra's enduring legacy continues to influence generations of performers and remains an indelible part of American popular culture.","Frank Sinatraa","carousel_images/e1bcd8dfceb8c5adf30d67bdffdfc3e7.jpg"],
            ["9","Pop","figure_images/justin.webp","Justin Bieber, a Canadian pop sensation, skyrocketed to fame as a teenager, captivating audiences worldwide with his angelic voice and boyish charm. Born on March 1, 1994, in Ontario, Bieber's journey to stardom began with homemade YouTube videos, catching the attention of talent manager Scooter Braun. His debut single 'Baby' became an international hit, solidifying his status as a teen heartthrob. Despite facing controversies and personal struggles in the public eye, Bieber's resilience and talent have propelled him to continued success. With numerous chart-topping albums and collaborations, Bieber's influence extends beyond music, making him a cultural icon of his generation.","Justin Bieber","carousel_images/642592.jpg"],
            ["10","Pop","figure_images/katy.jpg","Katy Perry, an American singer-songwriter, burst onto the music scene in the late 2000s with her infectious blend of pop anthems and colorful persona. Born Katheryn Elizabeth Hudson on October 25, 1984, in California, Perry's career took off with her hit single 'I Kissed a Girl' from the album 'One of the Boys.' Known for her bold fashion sense and vibrant stage presence, Perry has continued to dominate the charts with chart-topping albums like 'Teenage Dream' and 'Prism.' Beyond music, she's recognized for her advocacy work and philanthropy. Perry remains an influential figure in pop culture, captivating audiences with her catchy melodies and empowering lyrics.","Katy Perry","carousel_images/601626.jpg"],
            ["11","Pop","figure_images/taylor.webp","Taylor Swift, an American singer-songwriter, rose to prominence in the mid-2000s with her country-infused pop sound and heartfelt lyrics. Born on December 13, 1989, in Pennsylvania, Swift's debut self-titled album garnered widespread acclaim, showcasing her songwriting prowess and storytelling ability. With albums like 'Fearless,' 'Speak Now,' and '1989,' she has consistently topped charts and amassed a dedicated fanbase worldwide. Swift's evolution as an artist, transitioning from country to pop, has showcased her versatility and musical growth. Beyond music, she's known for her advocacy for artists' rights and social causes. Swift's impact on the music industry and pop culture is undeniable, solidifying her status as one of the most influential artists of her generation.","Taylor Swift","carousel_images/340432.jpg"],
            ["12","Pop","figure_images/ariana.png","Ariana Grande, an American singer, actress, and songwriter, has captivated audiences worldwide with her powerful vocals and undeniable talent. Born on June 26, 1993, in Florida, Grande began her career in the entertainment industry as a child actress on Broadway before transitioning to television, starring in Nickelodeon's 'Victorious' and 'Sam & Cat.' However, it was her music career that propelled her to superstardom, with chart-topping albums like 'Yours Truly,' 'My Everything,' and 'Dangerous Woman.' Grande's distinctive vocal range, combined with her soulful performances and catchy pop hits, has earned her numerous awards and accolades. Beyond music, she's known for her philanthropy and activism, using her platform to advocate for social justice causes. Grande's influence extends far beyond the realm of music, making her a cultural icon of her generation.","Ariana Grande","carousel_images/d46887391a6e2f1f36d7d558f9fc4d88.jpg"],
            ["13","Rock","figure_images/greenday.jpg","Green Day is a renowned American punk rock band formed in 1986. Comprising Billie Joe Armstrong, Mike Dirnt, and Tré Cool, the band emerged from Berkeley, California's punk scene. Their breakout album, 'Dookie' (1994), featuring hits like 'Basket Case,' propelled them to mainstream success. Known for their politically charged lyrics and catchy melodies, Green Day has left an indelible mark on the music industry. Albums like 'American Idiot' (2004) and '21st Century Breakdown' (2009) showcased their evolution and societal commentary. Beyond music, they've been vocal advocates for various causes, including environmentalism and LGBTQ+ rights. Green Day's influence extends far beyond their music, with their energetic performances and enduring relevance in popular culture making them icons of the punk rock genre.","Green Day","carousel_images/g.jpg"],
            ["14","Rock","figure_images/queen.jpg","Queen, a British rock band formed in 1970, stands as one of music's most iconic acts. Led by the charismatic Freddie Mercury, with Brian May, Roger Taylor, and John Deacon, their blend of rock, pop, and opera broke new ground. Their anthem 'Bohemian Rhapsody' remains a pinnacle of musical achievement. Albums like 'A Night at the Opera' (1975) and 'The Game' (1980) solidified their status as rock legends. Known for their theatrical performances and Mercury's dynamic stage presence, Queen has left an indelible mark on music history. Despite Mercury's untimely death in 1991, their music continues to inspire generations of fans worldwide.","Queen","carousel_images/download.jpg"],
            ["15","Basketball","figure_images/58419c8da6515b1e0ad75a63.png","The Cleveland Cavaliers, founded in 1970, are a professional basketball team based in Cleveland, Ohio, competing in the Eastern Conference of the NBA. The team has had notable successes, winning their first NBA Championship in 2016. Led by iconic players like LeBron James, the Cavaliers have established themselves as a force in the league. Despite challenges and roster changes, the team maintains a dedicated fan base and continues to strive for excellence on the court. With a rich history and passionate supporters, the Cavaliers remain a prominent figure in the NBA landscape, embodying resilience and determination in their pursuit of success.","Cleveland Cavaliers",""],
            ["16","Basketball","figure_images/58419ca3a6515b1e0ad75a64.png","The Philadelphia 76ers, established in 1946, are a renowned professional basketball team based in Philadelphia, Pennsylvania, competing in the Atlantic Division of the Eastern Conference in the NBA. With a storied history, the 76ers have won multiple NBA championships, including in 1955, 1967, and 1983. Over the years, the team has boasted legendary players such as Wilt Chamberlain, Julius Erving, and Allen Iverson. Known for their passionate fan base and iconic blue, red, and white color scheme, the 76ers continue to strive for greatness, with a focus on player development and team cohesion under the leadership of head coach Doc Rivers.","Philadelphia 76ers",""],
            ["17","Basketball","figure_images/58419ceda6515b1e0ad75a6a.png","The Houston Rockets, established in 1967, are a professional basketball team based in Houston, Texas, competing in the Southwest Division of the Western Conference in the NBA. With a history of success, the Rockets have clinched two NBA championships, in 1994 and 1995. Known for their innovative playing style, including an emphasis on three-point shooting and analytics-driven decision-making, the Rockets have left a significant mark on the league. Over the years, the team has been home to basketball icons like Hakeem Olajuwon, Clyde Drexler, and James Harden. Despite challenges, the Rockets continue to strive for excellence, with a focus on adaptability and resilience.","Houston Rockets",""],
            ["18","Basketball","figure_images/62066c9fd7b91b0004122608.png","The Los Angeles Lakers, established in 1947, are one of the most iconic and successful franchises in NBA history. Based in Los Angeles, California, the Lakers compete in the Pacific Division of the Western Conference. With an impressive record of 17 NBA championships, the Lakers boast a rich legacy built upon the contributions of legendary players such as Magic Johnson, Kareem Abdul-Jabbar, Shaquille O'Neal, and Kobe Bryant. Renowned for their 'Showtime' era and the 'Purple and Gold' color scheme, the Lakers hold a special place in basketball lore. With a devoted global fan base and a commitment to excellence, the Lakers continue to shape the NBA landscape with their storied history and ongoing pursuit of championships.","Los Angeles Lakers",""],
            ["19","Basketball","figure_images/58419bf3a6515b1e0ad75a59.png","The Toronto Raptors are a professional basketball team based in Toronto, Ontario, Canada. They compete in the Atlantic Division of the Eastern Conference in the NBA. Established in 1995 as part of the NBA's expansion into Canada, the Raptors have since become a prominent franchise in the league. The team won their first NBA championship in 2019, led by star players such as Kawhi Leonard, Kyle Lowry, and Pascal Siakam. Known for their passionate fan base, often referred to as 'Raptors Nation,' and their iconic red, black, and white color scheme, the Raptors continue to be a force to be reckoned with in the NBA.","Toronto Raptors",""]
        ]

        for row in data:
            figure, created = Figure.objects.get_or_create(
                id=row[0],
                figureGenre=row[1],
                figurePicture=row[2],
                figureAbout=row[3],
                figureName=row[4],
                carouselImage=row[5]
            )

            if created:
                self.stdout.write(self.style.SUCCESS(f'Created Figure {figure.figureName}'))
            else:
                self.stdout.write(self.style.WARNING(f'Figure {figure.figureName} already exists'))